name: Build Docker Image and Publish

on:
  push:
    #branches: #[ main ]
    #  - main
    tags:
      - 'v*'

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/posts
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push posts image
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:posts"
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          #tags: ${{ secrets.DOCKERHUB_USERNAME }}/posts:latest
      -
        name: Build and push comments image
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:comments"
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      -
        name: Build and push query image
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:query"
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      -
        name: Build and push moderation image
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:moderation"
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      -
        name: Build and push event-bus image
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:event-bus"
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
 