name: Build Docker Image and Publish

on:
  push:
    branches: [ main ]

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push posts image
        uses: docker/build-push-action@v4
        with:
          context: ./posts
          file: ./posts/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/posts:latest

      -
        name: Build and push comments image
        uses: docker/build-push-action@v4
        with:
          context: ./comments
          file: ./comments/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/comments:latest
      -
        name: Build and push query image
        uses: docker/build-push-action@v4
        with:
          context: ./query
          file: ./query/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/query:latest
      -
        name: Build and push moderation image
        uses: docker/build-push-action@v4
        with:
          context: ./moderation
          file: ./moderation/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/moderation:latest
      -
        name: Build and push event-bus image
        uses: docker/build-push-action@v4
        with:
          context: ./event-bus
          file: ./event-bus/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/event-bus:latest

